name: Deploy To EKS

on:
    workflow_run:
      workflows: 
        - Trivy Image Scan Workflow
      types:
        - completed
  
jobs:
    build:
      name: Deploy To EKS
      runs-on: self-hosted
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Pull the Docker image
          run: docker pull codewithmuh/react-aws-eks-github-actions:latest

  
        - name: Update kubeconfig
          run: aws eks --region us-west-1 update-kubeconfig --name EKS_cluster_codewithmuh
  
        - name: Deploy to EKS
          run: kubectl apply -f deployment-service.yml --validate=false


  
  